### ISSUE TITLE
toolchain 2016.03 (4.8.5) and kernel driver modules

### ISSUE THREAD

**Issue by ekromskoy** [foss-for-synopsys-dwc-arc-processors/toolchain#120]
Hi,

I have precompiled for our platform 4.8.4 ARC toolchain. At this time I want to compile 4.8.5 toolchain. I have verything working. I can use my toolchain to compile kernel and kernel modules however when I try to insert module (even simple one I use for test) I get "unknown relocation: 49" error. If I compile module using 4.8.4 toolchain there is no problem and module works fine, even though kernel itself compiled by my newer 4.8.5 toolchain. I checked all compilation flags, etc and they seems to be same for both toolchains.

I tried ARC700 pre-compiled 4.8.5 toolchain from this site and also getting this relocation error. Tried to add -fno-pic flags to module but it doesn't make difference (seems kernel and modules already have that).

Do you have any ideas? I appreciate any help.

Thank you,
Ed

**Comment by ekromskoy** [comment]
Just to clarify: I work with 3.12 kernel and looked thru latest 3.12.74 source code and there is no any support for 0x31 relocation type for ARC.

**Comment by vineetgarc** [comment]
Hi Ed,

ARC GNU 2016.03 added some major rework to dwarf debug info generation (e.g. support for assembler CFI psuedo ops; gas (as opposed to gcc) generating dwarf info etc). One of the important change was defaulting to .eh_frame (vs .debug_frame). This last part was a killer as it required support for a new relocation in kernel module loader etc (which eventually got added later). The quick fix for your 3.12.x is to over-ride this toolchian behaviour by cherry-picking upstream kernel fix f52e126cc74761 ("ARC: unwind: ensure that .debug_frame is generated (vs. .eh_frame)"). 

This will solve your immediate issue, but note that dwarf unwinding in kernel would still be broken as there was a bug in ARC gas in 2016.03 which was fixed in GNU 2016.09. See
https://sourceware.org/ml/binutils/2016-06/msg00443.html

Anyhow, I would recommend to wait for a few weeks and upgrade directly to upcoming 2017.03 GNU release which has this fixed  (and has a shining new gcc 6.2.y compiler as well)

FWIW, the kernel workaround patch could not stable back ported (to say 3.12) as stable maintainers typically discourage patches which allow old kernel with new compilers - see one of my arguments with gkh @ http://lists.infradead.org/pipermail/linux-snps-arc/2016-September/001470.html

HTH,
-Vineet
