### ISSUE TITLE
ARC GNU 2017.03 - CUnit build into baremetal throws a SIGSEGV on  _vfiprintf_r ()

### ISSUE THREAD

**Issue by coco21** [foss-for-synopsys-dwc-arc-processors/toolchain#145]
Hello,

We build CUnit v2.1-3 as a static libcunit.a lib and link it with our baremetal application.
Aim here is to unit test by using CUnit.

So far all goes well, build passes with no errors, and application even starts up until we hit  CU_ASSERT macro. There we get a SIGSEGV from the ARC GNU debugger. In our linker scripts ee defined a stack section and also a heap one. Stack is well initialized in our startup.s code and works as expected but we have no specific heap manager. The SIGSEGV is thrown on _vfiprintf_r () function.

Certainly a simple fix but I don't see it yet, any idea?

Thx Christophe

**Comment by anthony-kolesov** [comment]
Hi Chris,

I need more details on this:

1. SEGSEGV happens in the application and is reported by the debugger? Or it is the debugger that crashes?
2. What invokes the _vfiprintf_r function? Your code or cunit? It looks like that function doesn't supported floating point arguments, could that be the reason?
3. Is there a simple test case you can share that I can do on my side to reproduce the problem?

**Comment by coco21** [comment]
Hello Anthony,

Thanks for your quick reply.

1. Yes, the SIGSEGV is reported by ARC GNU GDB debugger
2. It's from our application main() function we invoke CU_ASSERT(1); and it directly crashes
3. Test case I've to check since there is sensitve stuff I first need to cut out takes time, no guarantees let me check

We code a baremetal application, no OS, no special heap manager and so.
Compiler switches for our application (and so was also built the libcunit to keep things alinged of course) mainly are:

-mlittle-endian
-mcpu=arcem
-mbarrel-shifter
-mmpy-option=0
-mcode-density
-mswap
-mnorm
-f-no-jump-tables
-mlong-calls
-mno-sdata
-specs=nonsys.specs

Thx Christophe

**Comment by anthony-kolesov** [comment]
I'm a bit confused, because as far as I know SIGSEGV cannot happen as is in the baremetal application, because this is a type of error that is reported by the OS. Baremetal application on invalid memory access would go to an exception handler for memory error events and depending on implementation debugger wouldn't know about that or would get an unexepcted halt of application. IIRC your are using a custom designed simulator, so SIGSEGV is probably reported by the simulator. Or are you seeing this with a hardware, then what is the GDBserver you are using? I think that GDBservers that I work with myself, would report a different error code. What is the instruction where execution halts - is it a hardcoded `flag 1` for processor to selfhalt, or is it a breakpoint inserted by the debugger?

If I understand correctly, you invoke CU_ASSERT(1), but it halts in the _vfiprintf_r () ? Is CU_ASSERT expected to print anything on success? Is it possible to disable all printing from CUnit, to see if this changes anything? Do you have any type of hostlink library used? `nosys.specs` contains stubs for `write_()` which just return error code - this shouldn't cause memory errors, but I'm not sure in this.

**Comment by coco21** [comment]
We are using OVP/Imperas simulation as the executing target that also comes with its own GDBserver. I was first thinking about a missing heap manager because there is no such but understood C-runtimes provide for this already, am I correct in my understanding? So this cannot be the correct lead.

I rather think you may be right here and I need to discuss this with Imperas since I cannot simply provide you with the sample code and runtimes and licenses needed.

Let me know. Thx Chris

**Comment by anthony-kolesov** [comment]
I believe malloc should work fine with a newlib baremetal - it just needs a .heap section to work.

**Comment by coco21** [comment]
Ok great it's what we did, so that one we can put aside. I just got an answer from Imperas, looks like they can help here and are the right person for the moment, I keep you up to speed and let you know about the findings of course. Thx Chris

**Comment by coco21** [comment]
Hello Anthony,

The problem finally was in kind of runtimes being used both on application and static lib build and also on what the simulator target was expecting of such a setup. We can close this case, thanks for our time and merry X-mas and all the best for 2018, cheers Chris
