### ISSUE TITLE
Unable to link with libraries precompiled with MetaWare

### ISSUE THREAD

**Issue by andreapast** [foss-for-synopsys-dwc-arc-processors/toolchain#158]
Hello,
I'm trying to compile a test application linking static libraries compiled with Synopsys MW.
The test application was supplied with Makefile and linker scripts for MW package, 
which I modified to adapt it to the GNU toolchain, which I would use in place of MW.

The hardware architecture is an ARC600 SoC including an internal ROM (with some read-only libraries on it), and internal RAM (for both user code and user data).
At startup the hardware will copy an amount of data from an external ROM to the internal RAM,
then execution will jump to internal RAM.

Compilation goes fine, analyzing the .o file with objdump I see nothing wrong.
When I link however, I receive an error where sections seem to be allocated in the wrong memory segment, but I'm not able to understand why.

I'm attaching the linker log 
[linker.log](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/2301936/linker.log)

the original scripts
[memmap.script.txt](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/2301939/memmap.script.txt)
[ld_app.script.txt](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/2301940/ld_app.script.txt)
[ld_rom.script.txt](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/2301942/ld_rom.script.txt)

and the modified script
[linker.script.txt](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/2301944/linker.script.txt)

Anybody may give me an advice about this problem?

Thanks
Andrea

**Comment by anthony-kolesov** [comment]
Hi Andrea,

I can reproduce similar error messages from the linker using a very simple application, so it looks like that error itself is not related to usage of metaware libraries.

As far as I can tell, the problem is in the `ALIGN(XX)` expressions you've put for .text and .data section. In linker scripts this place (after output section name) is to specify section address to override the automatic address calculated from the memory region assignment. As a result in your case .text section is assigned to address immediately after .text_intvec section aligned to 16 bytes, but that is outside of ISRAM region. Similarly .data is assigned to an address in the ISRAM_UPPER region.

To correct this problem you need to move those ALIGN statement after the semicolon, like this:
```
    .text : ALIGN(16)
    {
        _ftext = .;
        _start = .;
        *(.text.startup)
```

See section 3.6.1 of **share/doc/ld.df** in the toolchain prebulit or https://sourceware.org/binutils/docs/ld/Output-Section-Description.html#Output-Section-Description
for specification:
```
section [address] [(type)] :
  [AT(lma)]
  [ALIGN(section_align) | ALIGN_WITH_INPUT]
  [SUBALIGN(subsection_align)]
  [constraint]
  {
    output-section-command
    output-section-command
    …
  } [>region] [AT>lma_region] [:phdr :phdr …] [=fillexp] [,]
```

**Comment by andreapast** [comment]
Hello Anthony,
you are right! This was a copy-paste typo from the original scripts. 
It seems MW has a slightly different syntax...

Thanks
Andrea

**Comment by anthony-kolesov** [comment]
Yes, Metaware has different linker script syntax, unfortunately...
