### ISSUE TITLE
Bare metal and .data initialization problem

### ISSUE THREAD

**Issue by andreapast** [foss-for-synopsys-dwc-arc-processors/toolchain#159]
I'm trying to develop a bare metal application on a SoC with ARC600.
I successfully compiled an .elf file using the toolchain, but it doesn't run on real hardware.
I tried to check for obvious errors with objdump (memory sections and addresses), all seems fine.

Memory area 0x00000-0x7FFF is an internal ROM including read-only libraries and software.
Memory area 0x40000-0x76FFF is an internal instruction RAM.
Memory area 0x80000000-0x80028000 is an internal data RAM.
The SoC hardware at start copies data from an external FLASH to RAM area 0x40000-0x76FFF.

The memory layout is:
    ROMVECT(RX)             : ORIGIN = 0x00000000,         LENGTH = 0x0400
    ROM(RX)                 : ORIGIN = 0x00000400,         LENGTH = 0x7C00
    RAMVECT(RWX)            : ORIGIN = 0x00040000,         LENGTH = 0x0180
    ISRAM(RWX)              : ORIGIN = 0x00040180,         LENGTH = 0x36E80
    ISRAM_UPPER(RWX)        : ORIGIN = 0x00077000,         LENGTH = 4K
    DSRAM_OS(RWX)           : ORIGIN = 0x80000000,         LENGTH = 8K
    DSRAM(RW)         	    : ORIGIN = 0x80002000,         LENGTH = 152K
    FLASH(RX)               : ORIGIN = 0xC0000000,         LENGTH = 512K

objdump -h reports several sections, whence the following:

Idx Name          Size      VMA       LMA       File off  Algn
  0 .text_librom  00003ffc  00000400  00000400  00000400  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  1 .data_librom  00000044  80000000  000043fc  00006000  2**2
                  CONTENTS, ALLOC, LOAD, DATA
  2 .sbss_librom  00000000  80000044  00004440  0002a044  2**0
                  ALLOC
  3 .bss_librom   00001da4  80000044  80000044  0002a044  2**2
                  ALLOC
  4 .text_intvec  00000100  00040000  00040000  00008000  2**4
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  5 .text         0001f200  00040180  00040180  00008180  2**4
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  6 .text_upper_iram 00000000  00077000  00077000  000294c4  2**0
                  CONTENTS
  7 .data         000014c4  80002000  0005f380  00028000  2**2
                  CONTENTS, ALLOC, LOAD, DATA
  8 .sbss         00000000  800034c4  800034c4  000294c4  2**0
                  CONTENTS
  9 .bss          00009c14  800034c4  800034c4  000294c4  2**2
                  ALLOC
 10 .stack        00002000  8001c000  8000d0d8  0002a000  2**0
                  ALLOC
 11 .heap         0000a000  8001e000  8000d0d8  0002a000  2**0
                  ALLOC
 12 .text_flash   00000000  c0000000  c0000000  000294c4  2**0
                  CONTENTS

I'm checking particularly .data: it's located in RAM at 80002000 and should be copied 
at start from 0005f380.

I disassembled to check startup code:

IVT seems ok, the first vector (reset) jumps to __start

00040000 <$t>:
   40000:	2020 0f80 0004 0180 	j	0x40180

__start does something (set registers sp, gp, and other), then branches to _init

00040180 <__start>:
   40180:	220a 3f80 8000 2000 	mov	gp,0x80002000
   40188:	72cf 8000 34c4      	mov_s	r2,0x800034c4
   4018e:	2602 7083 8000 d0d8 	sub	r3,0x8000d0d8,r2
   40196:	2b42 80bc           	asr.f	lp_count,r3,0x2
   4019a:	20e8 03a2           	lpne	0x1c	;401b4 <__start+0x34>
   4019e:	2740 7503           	add	r3,pcl,0x14	;401b0 <__start+0x30>
   401a2:	236b 0080           	sr	r3,[lp_start]
   401a6:	240a 3f80 8001 e000 	mov	sp,0x8001e000
   401ae:	db00                	mov_s	r3,0
   401b0:	1a04 00d0           	st.ab	r3,[r2,4]
   401b4:	7508                	mov_s	r13,r0
   401b6:	7628                	mov_s	r14,r1
   401b8:	1204 3001           	ld	r1,[gp,4]
   401bc:	70cf 0005 8cc6      	mov_s	r0,0x58cc6
   401c2:	2180 0305           	add	r1,r1,332
   401c6:	19fc 8040           	st	r1,[r1,-4]
   401ca:	a102                	st_s	r0,[r1,0x8]
   401cc:	d801                	mov_s	r0,0x1
   401ce:	a101                	st_s	r0,[r1,0x4]
   401d0:	0af2 0c40           	bl	101104	;58cc0 ;<_init ;> 
   401d4:	70a9                	mov_s	r0,r13 
   401d6:	71c9                	mov_s	r1,r14 
   401d8:	0812 0020           	bl.d	16	;401e8  ;< main ;> 
   401dc:	234a 3000           	mov	fp,0 
   401e0:	2020 0f80 0005 6544 	j	0x56544 

_init does something strange???
Does it loops indefinitely??

00058cc0 <_init>:
   58cc0:	c0f1                	push_s	blink
   58cc2:	0000 0000           	b	0	;58cc0 <_init>

Maybe there's something wrong in linker parameters? 
I used arc-elf32-gcc -mcpu=arc600 -mbarrel-shifter  -static --specs=nosys.specs -T linker.script

Thanks
Andrea

**Comment by anthony-kolesov** [comment]
It seems that contents of **_init** is constructed from multiple **crt\*.o** files and with your linker script this doesn't happen.

Standard GNU linker script (arc-elf32/lib/ldscripts/arcv2elfx.x), has this for init:
```
  .init           :
  {
    KEEP (*(.init))
  }  > text  =0
```

Note that this this a separate section, located in the memory region for instruction memory, before the **.text** section. So in your case you'd need to insert between **.text_intvec** and **.text**:
```
  .init : ALIGN(16)
  {
    KEEP (*(.init))
  }  > ISRAM
```

I haven't checked this, so can't confirm that this is an exact solution, but, I think, it should be something similar to this.

**Comment by andreapast** [comment]
Thanks for your invaluable help!
I will try this solution, however maybe it will not be enough in this
special case.

I'm compiling a .c file, while linking the related .o plus two precompiled
.a coming from MW.
While the .c/.o compiled with GCC will be handled as expected, but I'm
afraid something will go wrong with the .a, due to different section names
and load methods.

The original script ld_app.script for MW includes an INITDATA directive, so
the MW linker is directed to generate a .initdata section and _initdatacopy
function, to be called for initialization.
If the .a files where compiled with the same directive, I think I should
call this function somewhere...

Given that I could merge all source data sections in one with contiguous
area, I could also tweak the GCC symbols _fdata and _edata to force the
linker to load the whole .data section, including foreign sections coming
from .a.

Could it be an idea?

Thanks
Andrea

**Comment by anthony-kolesov** [comment]
Section names should be compatible between MW and GCC, it is proven that it is possible to link application using GCC linker and libraries, though this was done for newer ARC processors and manual how to do this is not public... But I don't think section names would cause problems, especially since you are writing own linker script anyway, so can merge difference sections into one final section.

init instructions also should come only from one toolchain, in your case it is GNU toolchain, because you don't use option `-nostartfiles`. Hence there shouldn't be any conflicts, though I'm not sure if MW libraries would work in this case, but I think they would.

I'm not sure sure what do you mean by " force the linker to load", because technically linker doesn't load anything - it only creates ELF file. How this ELF is converted to a desired format, loaded into flash memory and then copied from flash to SRAM - all of this is specific to your particular application, gnu toolchain doesn't have any special code to implement this, though there is no reason why this can't be implemented with custom code.

**Comment by andreapast** [comment]
I will try to explain in another way what I understood about MW, but I'm
not an expert at all.
Specifying INITDATA section in MW linker script, the specified section
(.data) will be treated as .bss (zeroed or uninitialized), while the linker
will create the initialization section with init data in .initdata, then
also a function named _initdatacopy will be added to the object file, which
will copy .initdata to .data when invoked.
Given this, I think that the startup code added by the linker will not
initialize anymore, while the function will be invoked by other code (not
clear to me by who or when).
Furthermore, the .initdata section could be compressed, so maybe this
couldn't be simply copied, but could need some processing to reconstruct
original data.

Thinking of GCC, if I understand the whole startup sequence correctly, the
_init function should copy initialization data from section .init (normally
ROM) to .data (RAM).
I suppose that the standard code of GCC performing this operation (crt0.S
?) will use some symbols created by the linker and specifying source
address and destination address, and size as well.
Of course these symbols will be computed from what GCC knows and can handle
(code compiled by GCC, or at least with same mode of operation)... so maybe
in the end only GCC variables will be correctly initialized...

On the other side, if the .initdata from MW were plain uncompressed data,
if I specified in the linker script to put .init and .initdata adjacent and
aligned in a single .init output section, and in the same way .data from
GCC compiled .o and .data from MW compiled files to a single .data, and
again specifying _fdata and _edata from the merged .data, then the routine
from GCC will copy initialization data for both MW and GCC variables.

What do you think?

**Comment by andreapast** [comment]
Hello Anthony,
thanks to your suggestions I made a leap ahead.
As I have .elf and .map files from MW, related to the very same project I'm trying to build in GNU,
I tried to compare the .map files, and these are very similar now.
I also checked the start code of the GNU .elf, and now _init includes code also from the libraries.

Unfortunately, if I try to execute it, it doesn't work. No clue about the reason.
A small difference between MW and GNU is that MW compiled with -Hnoxcheck and -Hnoxcheck_obj,
while in GNU I didn't found an option to avoid it.
But I'm not sure of this will make a real difference.

I included the two map files, in case you have some ideas to help me to have this code running...

[test_gpio.map.MW.txt](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/2309922/test_gpio.map.MW.txt)
[test_gpio.map.GNU.txt](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/2309925/test_gpio.map.GNU.txt)

Maybe I could try to simulate it with nSIM?
Andrea

**Comment by anthony-kolesov** [comment]
> Given this, I think that the startup code added by the linker will not
> initialize anymore, while the function will be invoked by other code (not
> clear to me by who or when).

I don't think so, because it is also metaware startup code that would call such a function. Since GNU toolchain will link GNU startup code this function will not be called as well.

> Thinking of GCC, if I understand the whole startup sequence correctly, the
> _init function should copy initialization data from section .init (normally
> ROM) to .data (RAM).
> I suppose that the standard code of GCC performing this operation (crt0.S
> ?) will use some symbols created by the linker and specifying source
> address and destination address, and size as well.

Unlikely. GNU _init code for a simple application is this: 
```
00000104 <_init>:
 104:   c0f1                    push_s  blink
 106:   2700 7f8c 0000 015c     add     r12,pcl,0x15c   ;260 <frame_dummy>
 10e:   2022 0300               jl      [r12]
 112:   2700 7f8c 0000 0318     add     r12,pcl,0x318   ;428 <__do_global_ctors_aux>
 11a:   2022 0300               jl      [r12]
 11e:   c0d1                    pop_s   blink
 120:   7ee0                    j_s     [blink]
```
There is no copying of data here or in invoked functions. crt0.s (https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/blob/arc-2018.09/libgloss/arc/crt0.S) does't lots of stuff, including initialization of **.bss** section, but it also doesn't copy any data -- all of this should be done by the debugger, bootloader or an application itself.

`-Hnoxcheck` tells metawware to not check whether application can be run on target hardware, GNU doesn't have this functionality therefore this options is not needed.

I can't say anything based on memory map, since there is too much stuff in them. I'd suggest attaching debugger to see where application is stuck, but I'd suspect that problem is that since GNU doesn't implement any handling of initdata section, it is not copied, hence application doesn't get data it expects. In this case I think you'd need to merge initdata and data into a single section, or recompile metaware libraries with option that disables initdata at all, or implement a function that would copy this initdata at startup.

**Comment by andreapast** [comment]
Hello,
I implemented a simple load function which will copy merged initialization data from IVRAM to DRAM in .data, and called it at start of main. Still nothing...
I also tried to call another function name rom_init present in the ROM area and called by the MetaWare startup code. Nothing...
I have no way to attach a debugger, maybe I could try to simulate?
I installed the toolchain ide and MWLite (only for Windows unfortunately) to obtain nSIM. 
Configured as in wiki, but where is the nSIM executable I would need to lauch?
I only find C:\MWLite\nSIM\bin\arcsvr.exe, but gives an error when launched from IDE...

**Comment by anthony-kolesov** [comment]
I never used MWlite, maybe nSIM included there is for metaware only, so GDBserver is not included? You can download free nsim at https://www.synopsys.com/cgi-bin/dwarcnsim/req1.cgi , though it will take some time, because downloads are manually approved.

Debugging this problem without debugger would be complicated. I would have tried building some application without metaware libraries, just to see if current linker map is correct at all and that code compiled by compiler can be run at this hardware - because processor is configurable, it is possible that compiler would use an instruction that is not actually present, unless told not to do so, this will cause a failure.

**Comment by andreapast** [comment]
Hello,
I was enabled to download nSIM.
Now I tried to build and debug the Hello World application on Eclipse.
I created a new project for ARC600 little-endian. Build ok.
Then tried to configure debugger, specifying nSIM as debugger, pointing executable to nSIM_64/bin/nsimdrv and choosing nSIM_64/etc/tcf/templates/arc601.tcf as processor file.
I disabled properties file.

On debugger run, it seem to start, then after some seconds I receive an error:
Breakpoint installation failed: Suspend operation timeout.

What's wrong?

Andrea

**Comment by anthony-kolesov** [comment]
If you haven't changed compiler options, then "ARC600" hello world will not run on arc601.tcf, because by default GCC compiler with option -mcpu=arc600 compiles code that uses features not available on arc601. You need to either use arc610d.tcf or arc625d.tcf. Another option is to pass -mcpu=arc601 to GCC, so it will build code for ARC 601, but it seems that this is not supported in IDE, so can be done only through command line.

**Comment by andreapast** [comment]
Hello,
I tried to switch the TCF to both arc610 and arc625, with no luck.
There's a temporary breakpoint on main, so after start the debugger should suspend entering main,
but it does not. I don't understand if the debugger hangs somewhere in the code, or if it doesn't start at all...

**Comment by anthony-kolesov** [comment]
Can you confirm that your compiler and debugger options look like this?
![compiler_options](https://user-images.githubusercontent.com/602123/44733547-7e249600-aaf0-11e8-8101-d73a88625180.PNG)
![debugger_options](https://user-images.githubusercontent.com/602123/44733562-841a7700-aaf0-11e8-9e6e-a2c692e060b0.PNG)

**Comment by andreapast** [comment]
Yes, it's exactly like in your images.

![screenshot_2018-08-28_17-00-17](https://user-images.githubusercontent.com/42537510/44734365-06ec0380-aaea-11e8-9e34-e5af9fd97422.png)
![screenshot_2018-08-28_17-40-53](https://user-images.githubusercontent.com/42537510/44734366-07849a00-aaea-11e8-824c-3e502008e6db.png)
![screenshot_2018-08-28_17-42-16](https://user-images.githubusercontent.com/42537510/44734368-07849a00-aaea-11e8-9416-5a07c34a3d03.png)

**Comment by anthony-kolesov** [comment]
No, you have "Load application into target" checked off. This means that GDB will not load ELF file into nSIM, so there is nothing to execute for nSIM.

**Comment by claziss** [comment]
Not sure if this issue still needs to be kept open. Please react if you don't want this thread to be close. Thank you.
