### ISSUE TITLE
Where is the source for tcftool?

### ISSUE THREAD

**Issue by petertorelli** [foss-for-synopsys-dwc-arc-processors/toolchain#167]
`tcftool` generates an error on a new install of Ubuntu 16.04:

~~~
$ cd arc_gnu_2019.03-rc1_ide_linux_install/bin
$ ./tcftool
bash: ./tcftool: No such file or directory
~~~

The other binaries in the release work (e.g., `arc*` and `openocd` in the `bin/` folder), so I'd like to rebuild `tcftool` to solve this problem but it is distributed as a binary in the source repo.

Thanks,
Peter

**Comment by shahab-vahedi** [comment]
Hi Peter,

I used to have the same problem on `Arch Linux`. I solved it by installing `lib32-gcc-libs`. It seems such package does not exist on Ubuntu but there must be some [other packages for running 32bit binaries](https://blog.teststation.org/ubuntu/2016/05/12/installing-32-bit-software-on-ubuntu-16.04/).

**Comment by anthony-kolesov** [comment]
Hi @petertorelli 

Unfortunately we can't provide sources for the **tcftool**, it's a proprietary tool, part of the Metaware toolset. However it seems the problem is not present in the current builds of **tcftool**, so I have updated the version in the toolchain repo: https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/commit/318d5c008b59f7acec326a21c378245e2f373b5c

This should become part of the upcoming 2019.03 release.

**Comment by petertorelli** [comment]
Hi @anthony-kolesov 
Tested and confirmed that the binary in the arc-dev branch solved the problem. Thanks for the fast response!
Peter
