### ISSUE TITLE
gdb fails when command "stepi" used near clone syscall

### ISSUE THREAD

**Issue by fbedard** [foss-for-synopsys-dwc-arc-processors/toolchain#190]
gdb fails when command "stepi" used near "trap_s" ARC assembly instruction.

I tried to debug userspace path of "clone" syscall from uClibc.

Here is part of code I tried to debug:
```
mov r0, r2  ; libc @flags is 1st syscall arg
mov r2, r4  ; libc @ptid
mov r3, r5  ; libc @tls
mov r4, r6  ; libc @ctid
mov r8, __NR_clone
trap_s 0

cmp r0, 0  ; return code : 0 new process, !0 parent
blt .L__sys_err2 ; < 0 (signed) error
jnz [blink]  ; Parent returns
```

Here is gdb out, when I executed code using "stepi" command:
```
0x200ad708 <clone+28>: mov        r0,r2
0x200ad70c <clone+32>: mov        r2,r4
0x200ad710 <clone+36>: mov        r3,r5
0x200ad714 <clone+40>: mov        r4,r6
0x200ad718 <clone+44>: mov        r8,220
0x200ad71c <clone+48>: trap_s     0
[New Thread 0x2001ca10 (LWP 111)]
0x200ad71e <clone+50>: cmp        r0,0
Program received signal SIGTRAP, Trace/breakpoint trap.
[Switching to Thread 0x2001ca10 (LWP 111)]
0x200ad71e <clone+50>: trap_s     1
0x200ad71e <clone+50>: trap_s     1
Program received signal SIGTRAP, Trace/breakpoint trap.
[Switching to Thread 0x2001ca10 (LWP 108)]
0x200ad722 <clone+54>: trap_s     1
0x200ad722 <clone+54>: trap_s     1
Program received signal SIGTRAP, Trace/breakpoint trap.
[Switching to Thread 0x2001ca10 (LWP 111)]
0x200ad71e <clone+50>: trap_s     1
0x200ad71e <clone+50>: trap_s     1
Program received signal SIGTRAP, Trace/breakpoint trap.
[Switching to Thread 0x2001ca10 (LWP 108)]
0x200ad722 <clone+54>: trap_s     1
0x200ad722 <clone+54>: trap_s     1
```

... And so on ...

If I tried to use instruction like "next" or "step" after first time "trap_s 1" execution occurred gdb hangs up (because in execute "trap_s 1" infinitely).

This problem occurred when I used gdb as well as I used gdbserver.
Target platform is nSIM HS38.
gdb/uClibc/linux image/etc are build using buildroot.
gdb version is 2016.03

**Comment by shahab-vahedi** [comment]
With the current [state](https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/tree/2dac47516529458fa1e6d69afa66ff49835517e4) of [arc-2019.09-gdb](https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/tree/arc-2019.09-gdb), this issue is not reproducible.

![stepi_around_traps](https://user-images.githubusercontent.com/16524902/67761775-442c8800-fa44-11e9-9959-87f60a60a4e9.gif)

For future references, I keep here the [example](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/3779554/gdb-stepi-issue.zip) I used.

uClibc Linux image used was compiled with `arc-2019.09` toolchain. This was tested with an **HSDK board**.
