### ISSUE TITLE
__atomic_compare_exchange_n generates extra cmp instruction

### ISSUE THREAD

**Issue by abrodkin** [foss-for-synopsys-dwc-arc-processors/toolchain#192]
As of today `__atomic_compare_exchange_n()` for ARC HS generates a bit non-optimal assembly.

That's what we have in the Linux kernel:
```
1:	llock   r3, [r0]
	brne    r3, r0, 2f
	scond   r2, [r0]
	bnz     1b
2:
```
and that's what's being generated by GCC's __atomic_compare_exchange_n():
```
1:	llock   r3, [r0]
	cmp_s r3, r1    <-- THIS
	bnz_s  2f   
	scond   r2, [r0]
	bnz_s    1b
2:
```

See that extra `cmp_s` in the critical section between `llock` & `scond`.

**Comment by abrodkin** [comment]
@vineetgarc does it make any sense to use `bnz_s` in the Linux kernel instead of today's `bnz` in the example above?

**Comment by vineetgarc** [comment]
well cmp + bnz is equivalent to a BRNE, what is the issue. It seems the overall code size of 2 snippets is the same,
I don't use the BNZ_S for retry branch as it causes the next instruction(s) to be unaligned which we know can sometimes cause BPU misgivings.

**Comment by abrodkin** [comment]
> well cmp + bnz is equivalent to a BRNE, what is the issue. It seems the overall code size of 2 snippets is the same

Indeed but doesn't decoding and issue costs of pair `cmp + bnz` differ from `brne` alone?

**Comment by vineetgarc** [comment]
Right, so the compiler guys can indeed optimize the cmp_s + bnz_s with a single BRNE. compilers tend to get a bit conservative since the branhc can technically get out of range (unless we feed it a specific toggle). You could argue that in this case it is gcc intrinsic so it can assume that the "small" segment of code would not get out-of-range. This depends on how the intrinsic is actually implemented. But in theory it should indeed be possible.

**Comment by abrodkin** [comment]
@claziss do you think it makes sense to consider described above optimization in GCC's `__atomic_compare_exchange_n()`?
If you don't see as a useful optimization, please close this one.

**Comment by claziss** [comment]
If anyone is in desperate need for this optimization please reopen.
