### ISSUE TITLE
Documentation building fails on Fedora 31 with texlive version below 2019-6.fc31

### ISSUE THREAD

**Issue by falaleevms** [foss-for-synopsys-dwc-arc-processors/toolchain#208]
Built in container fedora:31

Error:
```
make[2]: Entering directory '/home/auto_user/arc_gnu/bd-elf32/binutils/ld'
TEXINPUTS="/home/auto_user/arc_gnu/binutils/ld/../texinfo:$TEXINPUTS" \
MAKEINFO='makeinfo --split-size=5000000 -I /home/auto_user/arc_gnu/binutils/ld -I /home/auto_user/arc_gnu/binutils/ld/../bfd/doc -I ../bfd/doc -I /home/auto_user/arc_gnu/binutils/ld/../libiberty  -I /home/auto_user/arc_gnu/binutils/ld' \
texi2dvi -I /home/auto_user/arc_gnu/binutils/ld -I /home/auto_user/arc_gnu/binutils/ld/../bfd/doc -I ../bfd/doc -I /home/auto_user/arc_gnu/binutils/ld/../libiberty --pdf --batch  --build-dir=ld.t2p -o ld.pdf  \
`test -f 'ld.texi' || echo '/home/auto_user/arc_gnu/binutils/ld/'`ld.texi
/usr/bin/texi2dvi: TeX neither supports -recorder nor outputs \openout lines in its log file
```
 
Full log:
[elf32-build-2019-11-21-1140.log.txt](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/3877072/elf32-build-2019-11-21-1140.log.txt)

Reporduce:
```
# on ru20arcgnu1
docker run -it --rm fedora-31-pdf-fail
cd $HOME
/var/release-testing/toolchain-smoketest-tarball.sh
```

**Comment by abrodkin** [comment]
For now workaround is to disable building of documentation passing `--no-pdf` to `build-all.sh` script.

**Comment by abrodkin** [comment]
Could be reproduced on partially built toolchain (some intermediate files are required) like that:
```
$ cd binutils/ld
$ texi2dvi -I , -I ../bfd/doc -I ../libiberty --pdf --batch  --build-dir=ld.t2p -o ld.pdf ld.texi -I ../../bd-uclibc/binutils/ld/ -I ../../bd-uclibc/binutils/bfd/doc/

/usr/bin/texi2dvi: TeX neither supports -recorder nor outputs \openout lines in its log file
```

**Comment by abrodkin** [comment]
This is Fedora 31 bug: https://bugzilla.redhat.com/show_bug.cgi?id=1772624
The fix is to be deployed via newer version of texlive package. It must be of version `2019-6.fc31` or above. As of today (November 22-nd 2019) this package version was only available from Fedora testing repository and it's possible to get it via addition of the corresponding repo, see https://bodhi.fedoraproject.org/updates/FEDORA-2019-88ffe47587.

Basically we need to:
```
sudo dnf upgrade --enablerepo=updates-testing --advisory=FEDORA-2019-88ffe47587
```
before installing packages (otherwise once again we'll be downloading and installing 6000 packages).

Once this repo is added do normal installation of packages from prerequisites and do a nornal build.
Whenever this fix is available via standard update repos and/or becomes a part of Fedora 31 Docker image we won't need above trick any longer.
