### ISSUE TITLE
build-all.sh doesn't remove previous INSTALL directory. 

### ISSUE THREAD

**Issue by anthony-kolesov** [foss-for-synopsys-dwc-arc-processors/toolchain#22]

**Comment by jeremybennett** [comment]
That is the intended behavior. What is the context in which you want something else?

**Comment by anthony-kolesov** [comment]
I've built ELF32 toolchain for some purpose, then I've built uclibc toolchain for another purpose. In the result I have them both in INSTALL  which is not what I've wanted. I can of course remove it manually before build but I forget about that. So I have to remove elf32 files manually.

**Comment by simonpcook** [comment]
I've had this behaviour set before for other tool chains with disastrous results when it is not obvious that we delete this directory. The example `./build-all.sh --install-dir /usr/local` shows why we don't at least want this as a default (theres no reason it can't be an additional `--remove-old-install` option, but it really shouldn't be the default.

**Comment by vineetgarc** [comment]
Actually if the install folder already exits (and is not empty) then the user can be warned and script can exit - no need to add any additional complexity. BTW scripts deleting stuff under the hood is VERY VERY bad idea conceptually. In pre 4.2.1 days I had my entire home folder wiped out because of a stupid rm -rf \* in a stupider script which GNU folks had then.

**Comment by anthony-kolesov** [comment]
Ok, I see your point.  Adding this as an option is more hassle than just removing this manually from shell. Closing.
