### ISSUE TITLE
Hackbench time equals exactly 1 second after rt-tests package update

### ISSUE THREAD

**Issue by falaleevms** [foss-for-synopsys-dwc-arc-processors/toolchain#311]
From this [hackbench.log](https://github.com/foss-for-synopsys-dwc-arc-processors/linux/files/5575157/hackbench.log) you can see that we have launched hackbench 15 times and time always was exactly 1 second. I started to observe such results after buildroot rebase on top of the master branch ([2020.05-2290-gd00b6c7864](https://gitsnps.internal.synopsys.com/arc_oss/verification_automation/buildroot-verification-automation/-/tree/arcoss_v11_branch)), where rt-tests package was obviously updated as we have to apply [d00b6c7864594138a2ca7c5308dc9bbb6783b24c.patch.txt](https://github.com/foss-for-synopsys-dwc-arc-processors/linux/files/5575194/d00b6c7864594138a2ca7c5308dc9bbb6783b24c.patch.txt) to be able to build rt-tests package 

You can see this deviation on the chart:
![hackbench-diviation](https://user-images.githubusercontent.com/28342150/99831959-e8fa9580-2b70-11eb-9a5b-0ac5eca9660f.png)

**Comment by vineetgarc** [comment]
This is not related to Linux kernel version as I can reproduce it on 5.7 as well. Moreover running strace shows that Linux kernel is returning the right values.

```
clock_gettime64(CLOCK_REALTIME, {tv_sec=20, tv_nsec=615947704}) = 0
...
clock_gettime64(CLOCK_REALTIME, {tv_sec=23, tv_nsec=567731853}) = 0
```
I tried a bunch of old toolchains (and corresponding ramfs to test)
OK:	ramfs_1907-GNU-2019-03-glibc-tiny 
OK:	ramfs_2007-GNU-2020-03-glibc-tiny
OK:	ramfs_2007-GNU-2020-03-glibc-hf-tiny
NOK:	BR/gcc-upstream-hf-hs4x/target-tiny
NOK:	ramfs_2011-GNU-2020-03-glibc-2.32-tiny

So turns out the the issue is related to glibc version upgrade from 2.30 to 2.32 (which was somehow missed when reporting the issue, everything else  binutils, gcc versions etc is irrelevant - and would have saved a bunch of time investigating if captured correctly to begin with).

One of the key changes in glibc 2.32 is ARC port switching to 64-bt time_t interface (vs. 32-bit) hence gettimeofday syscall now deals with 64-bit quantities.
```
_extension__ typedef signed long long int __int64_t;
__extension__ typedef __int64_t __time_t;
struct timeval
{
  __time_t tv_sec;
  __suseconds_t tv_usec;
};
```

But the issue is **not** related to 64-bit time math and a recent gcc fix in that area [arc: Refurbish adc/sbc patterns](https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/b92c22b144d063c4436a6693045ceb57d344c495) - which I ended up building and wasting yet more time.

The issue is much more mundane and I kicke dmyself for not inferring it sooner.
hackbench uses format specifier %lu to report time implying 32-bit quantity - hence truncates the 64-bit tv_secs, tv_usec

```
	gettimeofday(&start, NULL);
...
	gettimeofday(&stop, NULL);
	timersub(&stop, &start, &diff);
        printf("Time: %lu.%03lu\n", diff.tv_sec, diff.tv_usec/1000);
```

Fix is to change hackbench printf to use 64-bit values
```
-         printf("Time: %lu.%03lu\n", diff.tv_sec, diff.tv_usec/1000);
+        printf("Time: %llu.%03llu\n", diff.tv_sec, diff.tv_usec/1000);
```

And with that we see the right output
```
Running with 10 groups 400 process
Time: 0.916
```

**Comment by abrodkin** [comment]
@vineetgarc are you going to submit that fix to the RT-Tests? As of today they still don't have it, see https://git.kernel.org/pub/scm/utils/rt-tests/rt-tests.git/tree/src/hackbench/hackbench.c?h=v1.9-test#n512.
Also it IMHO worth adding the same fix to the Buildroot here https://git.buildroot.org/buildroot/tree/package/rt-tests so that we start getting sane results in the reports.
