### ISSUE TITLE
BUG: scheduling while atomic

### ISSUE THREAD

**Issue by L-leopold** [foss-for-synopsys-dwc-arc-processors/toolchain#314]
Hello!
when I was running my own project in HSdk board,  especially loading the weight file, the board system crashed like the picture show:

![2af1b7520394e907b2307a7c9bdf1e4](https://user-images.githubusercontent.com/64076445/102217791-13453600-3f18-11eb-8930-83080e93e32e.jpg)

sorry ,I do not know the reason ,please help  me.
Thank you.

**Comment by vineetgarc** [comment]
For us to investigate the issue and help, please provide details about
1. Linux kernel - version, .config, is this pristine upstream or does it have any changes from you
2. GNU toolchain version 
3. Build system: Buildroot vs. toolchain scripts
4. Test case which triggers this and possibly the kernel image which triggers this

**Comment by L-leopold** [comment]
Hello！ 
1.Linux kernel - version, .config, is this pristine upstream or does it have any changes from you：
I use Prebuild Linux Distribution for ARC HSDK 2018.01   ubuntu  linux
2.GNU toolchain version
I use  this ：
https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/releases/download/arc-2018.09-release/arc_gnu_2018.09_prebuilt_uclibc_le_archs_linux_install.tar.gz
to compile my project
When I run the YOLO v3 tiny on HSDK ,it always tips Segmentation fault like this . 
![d2ee23bec3a35f7b41cdcdd2204c323](https://user-images.githubusercontent.com/64076445/102422934-cc079400-4042-11eb-9e7e-9d477914d78c.jpg)

Oh, I use HS38 board .
![128ba56032c3fa416e03de8d6d057c9](https://user-images.githubusercontent.com/64076445/102422951-d7f35600-4042-11eb-92de-35a2cb11f569.jpg)

I saw the specification said the memory has 4GB ,but I  use free -m  order to test, it only has 775MB ,I do not know why?

**Comment by vineetgarc** [comment]
For start enable debug of fata signals - that will give some hint as to what is going on.
echo 1 > /proc/sys/kernel/print-fatal-signals

Then try debugging your application using gdb to see why it is segfaulting (is it running out of memory - is a malloc failing).
We don't know about your application so it is hard to say where the problem could be.

Does your application need more than 1 GB of memory ?
Indeed the board has 4 GB memory, but the default build only uses around 1GB

**Comment by L-leopold** [comment]
Thank you sir ！ I will check them ,and use gdb to debug it.
The log shows like this:
![7a97a52f2bc99861f1e83d01cb8fa0b](https://user-images.githubusercontent.com/64076445/102437747-02024380-4056-11eb-9a98-816d7d844a1e.jpg)

Sir ,since the default is 1GB, how to open all 4GB for use？
And ，I want  to know HS4x whether 1GB memory is used by default ，will I meet the same problem when I am using HS4x board?

**Comment by L-leopold** [comment]
Yes ,when I run the YOLOv3 network , the PC shows it needs 2GB memory at least.
Thank you sir!
Thank you for your explanation.

**Comment by claziss** [comment]
@L-leopold any reason why you use the 2018 release? I would recommend using our latest 2020.09 release.

**Comment by L-leopold** [comment]
Well, this question is that  I can not run the Openmp with 2020 release. I originally planned to report this bug to you after running a YOLO version. Since you asked, I will tell you about this problem. I use the following steps:
1. git clone https://github.com/lapesd/libgomp.git
2. cd libgomp/src/libgomp/build
3. ../configure -host=arc-linux CC=arc-linux-gcc CXX=arc-linux-g++ -disable-multilib
4. make 
When I was running make step, it prompts like this:
![image](https://user-images.githubusercontent.com/64076445/102479265-a3f74f80-4099-11eb-9eb6-fea5fb5d3dc5.png)
Even I substitute CXX=arc-linux-g++  with CPP=arc-linux-g++ , because I  check the makefile ,it does not contain CXX ,but it contains CPP.
But it still can not work.
But when I use the 2018 release , it works . And I do not know the reason.


And sir,could you  please tell me how to use all the memory? Because when I run the YOLO network, which is a CNN, PC can run perfectly with 2GB memory. That means my code is not fault. I guess it is very likely that the memory is not enough .

**Comment by claziss** [comment]
@L-leopold please make a new issue on the libgomp subject. Thanks!

**Comment by L-leopold** [comment]
Ok sir ,I will  close this issue  , thank you .

**Comment by abrodkin** [comment]
@L-leopold let me try to explain specifics of memory usage on ARC processors and implications on the Linux and applications on top of it.
1. For ARC processors with MMU (such as ARC HS38 & HS48) only 2 GiB of entire 32-bit (i.e. 4 GiB) address space is used for user-space applications, i.e. only addresses from 0 to 0x1fff_ffff are being translated by the MMU.
2. That in theory limits amount of memory which is available to any process running on top of the Linux kernel to 2 GiB.
3. But Linux kernel uses the top part (last 256 MiB) of that "translated memory space" for its own purposes AKA `vmalloc` area (remember the Linux kernel operates in the address space of the last executed process), thus your user-space process has now just 1.75 GiB.
4. We also have a "safety gap" in for of yet another 256 MiB region in between user-space addresses and aforementioned kernel's so-called `vmalloc` which leaves just 1.5 GiB of address space for any given process.

Now given some specifics of the HSDK board (which simplify and speed-up operation of high-speed peripherals like 1Gb/sec Ethernet & USB 2.0) we "artificially" limit amount of memory being used for both kernel and user-space to just 1GiB. That's why you see 1 GiB - memory used by the kernel ~ 750 MiB.

Still if that's a hard requirements we may quite easily add another ~750 MiB of memory to the usable pool, but that will require to at least re-build the kernel.

If you really-really need even more we may add more memory and have almost 4 GiB avaialble but due to limitations described above any given user-space process won't have access to more than 1.5 GiB and so you'll be able to utilize all 4 GiB of DDR unless you run multiple processes, each using a lot of memory.

That said unless you see explicit need for larger memory (i.e. if Out Of Memory killer starts to show-up that will be the sign to add more memory to the system) let's stay conservative and try to use your system as it is set now.

Let me know if my explanation is clear or you need more details and guidance.

**Comment by L-leopold** [comment]
@Alexey Brodkin
Thank you for your explanation .And I am sorry about this problem .
Although I do not seek for " Out Of Memory killer " ,it actually is lack of memory.
Because when I run my network(tiny version) In PC ,it needs at least 1G memory.
Could you please tell me how to re-build the kernel to add another 750M .I think 1.5GB is enough.
THANk you sir!



At 2020-12-17 20:28:31, "Alexey Brodkin" <notifications@github.com> wrote:

@L-leopold let me try to explain specifics of memory usage on ARC processors and implications on the Linux and applications on top of it.

For ARC processors with MMU (such as ARC HS38 & HS48) only 2 GiB of entire 32-bit (i.e. 4 GiB) address space is used for user-space applications, i.e. only addresses from 0 to 0x1fff_ffff are being translated by the MMU.
That in theory limits amount of memory which is available to any process running on top of the Linux kernel to 2 GiB.
But Linux kernel uses the top part (last 256 MiB) of that "translated memory space" for its own purposes AKA vmalloc area (remember the Linux kernel operates in the address space of the last executed process), thus your user-space process has now just 1.75 GiB.
We also have a "safety gap" in for of yet another 256 MiB region in between user-space addresses and aforementioned kernel's so-called vmalloc which leaves just 1.5 GiB of address space for any given process.

Now given some specifics of the HSDK board (which simplify and speed-up operation of high-speed peripherals like 1Gb/sec Ethernet & USB 2.0) we "artificially" limit amount of memory being used for both kernel and user-space to just 1GiB. That's why you see 1 GiB - memory used by the kernel ~ 750 MiB.

Still if that's a hard requirements we may quite easily add another ~750 MiB of memory to the usable pool, but that will require to at least re-build the kernel.

If you really-really need even more we may add more memory and have almost 4 GiB avaialble but due to limitations described above any given user-space process won't have access to more than 1.5 GiB and so you'll be able to utilize all 4 GiB of DDR unless you run multiple processes, each using a lot of memory.

That said unless you see explicit need for larger memory (i.e. if Out Of Memory killer starts to show-up that will be the sign to add more memory to the system) let's stay conservative and try to use your system as it is set now.

Let me know if my explanation is clear or you need more details and guidance.

**Comment by abrodkin** [comment]
> Although I do not seek for " Out Of Memory killer " ,it actually is lack of memory.
> Because when I run my network(tiny version) In PC ,it needs at least 1G memory.

I'm not sure how strict is that requirement and if it exists at all but unless you don't see OOM (Out-Of-Memory) killer being executed your memory utilization shouldn't be a problem. Can you get your test or application running in your current situation or not?

> Could you please tell me how to re-build the kernel to add another 750M .I think 1.5GB is enough.

Let's first figure-out what's going on in your system first and then we'll see how to improve the situation.

**Comment by L-leopold** [comment]
@abrodkin  OK sir . I will learn  how to  use gdb(sorry for the use of this tool, I am still a novice）.
Maybe you are right , the following is memory usage:
![b361455cc33e23562ad4c333afe5feb](https://user-images.githubusercontent.com/64076445/102560951-726c9b80-410e-11eb-888f-6000675c511d.jpg)
I will check the log as soon as possible, then come back.
Thank you for your explanation.
