### ISSUE TITLE
[DWARF] Full path of source files are not stored in elf files.

### ISSUE THREAD

**Issue by shahab-vahedi** [foss-for-synopsys-dwc-arc-processors/toolchain#344]
If you build a program for arc64 target with debug flags, the stored information is incomplete:
```
> arc64-elf-objdump -Wi hello.exe
   ...
  <14>   DW_AT_name        : (indirect string, offset: 0x0): crt0.S
   ...
```

However, for the 32-bit arc:
```
> arc-elf32-objdump -Wi hello.exe
...
   <14>   DW_AT_name        : (indirect string, offset: 0x0): /data/work/repos/arcgnu/bin_gdb/newlib/libgloss/arc/crt0.S
...
```

The issue causes a problem: **GDB cannot locate the source file**.
This can be either coming from how we save the DWARF information or the [arc-gnu-toolchain](https://github.com/foss-for-synopsys-dwc-arc-processors/arc-gnu-toolchain) building scripts. Most likely, later is the case.

You have the necessary files to play with.
[binutils-64-no-full-path.zip](https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/files/3989657/binutils-64-no-full-path.zip)

**Comment by shahab-vahedi** [comment]
The symptoms of this problem manifests themselves as the incapability of debugging `newlib` routines in baremetal programs. For instance

- `crt0.S` code is not shown:

![arc64-bad](https://user-images.githubusercontent.com/16524902/216967733-92ddc336-b4cc-4cc3-bc3a-21c55e8f8cf8.png)

compared to ARCV2 programs:

![arcv2-good](https://user-images.githubusercontent.com/16524902/216967776-82ec51c0-cb16-43aa-8e08-7d6870cb3d74.png)

- or stepping into `printf()`, `puts()`, etc. are just ignored.

**Update:**
Since the submission of this issue, things have deteriorated even further. There is no mention of `crt0.S` in any form in arc64 baremetal DWARF information.

[arc64-bad-debug-experience.tar.gz](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/10662868/arc64-bad-debug-experience.tar.gz)

**Comment by kolerov** [comment]
The issue is resolved by this Pull Request: https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/pull/39. I will just copy a description here:

`.S` is a format for assembler + macros (unlike `.s` - it's for poor assembler). If you put such file to `arc-elf32-gcc -E` then it will be preprocessed and GCC will expand all macros. Consider this `example.S` source file:

```
.file "hello"
.text








nop

nop
```

After this command line

```
$ arc-elf32-gcc -mcpu=archs -g -gdwarf-5 -E example.S -o example.s
```

we will get this `example.s`:

```
# 0 "example.S"
# 1 "/home/ykolerov/workspace/task_arc64_dwarf/as//"
# 0 "<built-in>"
# 0 "<command-line>"
# 1 "example.S"
.file "hello"
.text
# 11 "example.S"
nop

nop
```
GCC adds extra information for assembler like `# <n> <file>` lines. Also GCC shrinks `.S` file to make it more compact (if gaps are too big) and also adds these lines for assembler to make him know that a gap exists: "skip `<n>` line in `<file>` and put this information to `.debug_line`". Then `arc-elf32-as` always overwrites filename symbol if it meets a line number comment (`# <n> <file>`). I think it's described here: https://github.com/foss-for-synopsys-dwc-arc-processors/binutils-gdb/blob/arc-2022.09/gas/dwarf2dbg.c#L2812. Filename is overwritten even if you define it manually using `.file`.

`.file` has no sense if it used in `.S` file manually - it maybe overwritten by assembler after preprocessing stage. Also, it happens on every platform (e.g. Intel). On the other side, when you compile `.c` files you can see that GCC generates `.file` with the same name as in `# <n> <file>` after preprocessing. Intel and ARM don't use `.file` in there `.S` files in Newlib.

So, the question is: “Why `.file` even exists if it’s always overwritten?” Actually, it’s used properly whet it’s generated by the compiler with a valid name. If assembler cannot find a line with filename then the name from `.file` is used.

Thus, the easiest way to prevent the issue is just remove all `.file` directives:

1. Because they are useless in such context and lead to an undefined behavior like this issue.
2. Compiler does not need help in finding the filename.
