### ISSUE TITLE
arc-2021.09-rc1: gdb in glibc_le_archs_native is located in a wrong place

### ISSUE THREAD

**Issue by EvgeniiDidin** [foss-for-synopsys-dwc-arc-processors/toolchain#439]
In toolchain release arc-2021.09-rc1 in native glibc toolchain gdb is located in a wrong place:
```
find 2021.09-rc1/glibc_le_archs_native/ -name gdb
2021.09-rc1/glibc_le_archs_native/arc-snps-linux-gnu/debug-root/slowfs/ru20arcgnu1/arcoss_verification/arc-gnu-toolchain/workspace/builds/896/arc-archs-native-gnu/arc-snps-linux-gnu/sysroot/usr/include/gdb
2021.09-rc1/glibc_le_archs_native/arc-snps-linux-gnu/debug-root/usr/bin/gdb
2021.09-rc1/glibc_le_archs_native/arc-snps-linux-gnu/debug-root/usr/share/gdb
2021.09-rc1/glibc_le_archs_native/share/licenses/gdb
2021.09-rc1/glibc_le_archs_native/share/licenses/gdb/gdb
```
Correct location:
```
 $ find 2021.09-eng011/glibc_le_archs_native/ -name gdb
2021.09-eng011/glibc_le_archs_native/arc-snps-linux-gnu/sysroot/usr/include/gdb
2021.09-eng011/glibc_le_archs_native/bin/gdb
2021.09-eng011/glibc_le_archs_native/share/gdb
2021.09-eng011/glibc_le_archs_native/share/licenses/gdb
2021.09-eng011/glibc_le_archs_native/share/licenses/gdb/gdb
```

BTW, this gdb in rc1 is working fine.

**Comment by abrodkin** [comment]
That's not a bug but more of a peculiarity of a "native" toolchain built in a canadian cross way. I.e. in  `.../glibc_le_archs_native/bin` cross-compiled tools are being installed, and among other things was GDB client (which we typically use on x86 host for remote debugging), but in that case since our `HOST` is also ARC we got GDB client cross-compiled. And in fact it works on ARC, with only one note - it doesn't recognize "native" debugging.

That's indeed confusing, so we disabled build of GDB client, while for now keep target `gdb`  where it used to be in `.../glibc_le_archs_native/debug-root/usr/bin`.
