### ISSUE TITLE
gdb option 'set arc opella-target arcem'

### ISSUE THREAD

**Issue by eroom1966** [foss-for-synopsys-dwc-arc-processors/toolchain#46]
Hi Support,

I now have rudimentary debugging working with openocd and gdb.

I want to see the auxiliary registers of the ARC EM, I try to do this by the command
(gdb) set arc opella-target arcem

This allows me to see the auxiliary registers by typing
(gdb) info all-register

but I can no longer step the target, typing no longer has an effect
(gdb) stepi

any suggestions ?
my full set of gdb commands are as follows (client is a different machine to the host running openocd):
(gdb) set remotetimeout 60
(gdb) target remote win6403:3333
(gdb) load
(gdb) set arc opella-target arcem
(gdb) stepi

Thx
Lee

**Comment by anthony-kolesov** [comment]
`set arc opella-target arcem` is not for OpenOCD but for Opella-XD debug probe which uses it's own application. With openocd there is no need for additional commands. So don't issue `set arc opella-target` command and `info all-registers` should work fine. Although in current release of GDB it will show some registers that are not present in EM, because it uses a fixed set of registers, so it contains some registers from other ARC cores.

**Comment by eroom1966** [comment]
Thanks for the update, but using the technique you describe above, there are lots of missing registers, for example
r30
identity
lp_start
lp_end
ic_*
dc_*
irq_*

it is quite an extensive list of missing registers, I created a difference listing of aux/sys regs in the EM which do not get shown and it is about 76.
Can you advise how we can access these registers ?

Thx
Lee

**Comment by anthony-kolesov** [comment]
Hi, Lee,

lp_start and lp_end are certainly there. r30 is called "ilink2". ic_ and dc_ are indeed missing. AUX registers should be present with names like aux_irq_\* although the use names from the previous generation ARCompact ISA, so might not match EM. Sorry for that... Should be fixed in June release :)

It is possible to bypass GDB oddities by issuing direct commands to OpenOCD with `monitor`command of GDB. For example to read register you can use `reg` command:

```
(gdb) monitor reg ic_ivil
ic_ivil (/32): 0x00000000
(gdb) monitor reg idenity
idenity (/32): 0x00110041
(gdb) monitor reg aux_iccm
aux_iccm (/32): 0x00000000
(gdb) monitor reg aux_dccm
aux_dccm (/32): 0x80000000
```

`reg` understand registers names and uses same names as defined in ARCv2 ISA, and it should understand all relevant AUX registers, except for different FPU and DSP registers. To set register value:

```
(gdb) monitor reg aux_dccm 6
aux_dccm (/32): 0x00000006
(gdb) monitor reg aux_dccm
aux_dccm (/32): 0x00000006
```

Although there is no error-checking, and that DCCM registes will not be really changed in this case. Also changing values here might cause inconsistency with GDB's own cache, so it is better to use this only for regs, that are not present in GDB.

Even more raw access is to issue direct JTAG command to OpenOCD with `monitor arc jtag` commands - they will bypass internal caches of both OpenOCD and GDB, so writes to those registers are not safe - OpenOCD might later overwritevalue using one from its cache. That however should be safe to write registers unknown to OpenOCD. Those JTAG commands use register numbers, so they can access _any_ register:
- To read AUX register: `monitor arc jtag aux-reg 4`
- To read core register: `monitor arc jtag core-reg 30`
- And to write just add a value as a second argument, for example: `monitor arc jtag core-reg 30 1`

For unexistent registers it will behave read-as-zero/ignore-on-write, for read-only it will also be ignore-on-write.

**Comment by eroom1966** [comment]
Hi Anthony,

Excellent, this is what I needed.
Two more questions more to close this thread.

Do you know if the EM Starter kit has the MPU supported, I cannot access any of the MPU registers ?

Where are the exception vectors located, they seem to go to unexpected locations ?

Thx
Lee

**Comment by anthony-kolesov** [comment]
Hi Lee,

No MPU is not present.

Exception vector is at 0x0 address. That can be found through reading INT_VECTOR_BASE AUX register and can be modified by the application. Note that unlike some other architectures, on ARC exception vector entries contain the address of exceptions handlers, not the jump-to-exception-handler instructrion. crt0.S file that is mentioned in our guide should set exception handlers for all exceptions and internal interrupts, and that handler will simply halt the core. In this case vector table is stored in the elf file and loaded by the GDB at the specified address. The common problem that might happen is that core can appear like it "hanged" and doesn't do anything, and when halted it is at address 0x0 with 0 value at this address. That happens when vector table hasn't been configured, so there are zeros there, and then some interrupt (like timer) or exception happens, core follows address from respective vector table entry, which is 0, thus it lands with PC==0x0, treats it as instructrion, and there is another zero, and in ARC ISA instructrion encoded as 0x0 is branch to self, so core starts looping at this address.

**Comment by eroom1966** [comment]
Hi Anthony

Thanks for the clarification regarding the vectors this is indeed the problem, our vector table contained instructions to branch to an address, rather than the table being a jump table of addresses.
Q. Can you tell me, is this a change from ArcV1 ISA to ArcV2 ISA, I am pretty sure that in ArcV1 we used branch instructions ?

Regarding the MPU, I had no idea the this was not implemented, I did not see that in any of the documentation before purchasing the EM starter kit - did I miss something in the docs ?

Thx
Lee

**Comment by anthony-kolesov** [comment]
Yes, it is a change from ARCv1.

I think documentation for EM SK doens't mention MPU at all, which means that there is none. I've asked board developers and they say that it might be possible to fit MPU into, although that might be possible in the modified FPGA image at the expense of decreased core MHz and, maybe, by chopping off some another HW feature. Although they are not 100% sure - nobody asked for this before, so they are rather interested in the use case for that, so then they might consider adding such FPGA configuration to the next release (somewhere in summer). Do you have any exact use case for MPU?

Can I get some context for a project? Is that a hobby or you are an ARC licensee with support agreement? In the latter case you can use Solvnet, and maybe they will be able to help with obtaining EMSK FPGA image with MPU.

**Comment by anthony-kolesov** [comment]
Is there any reason to keep this open?

**Comment by eroom1966** [comment]
No, closing issue - thanks for support
