### ISSUE TITLE
norm instructions in em/libc.a?

### ISSUE THREAD

**Issue by jstraus59** [foss-for-synopsys-dwc-arc-processors/toolchain#48]
When I use the -mcpu=arcem option when using the prebuilt toolchain from:

  https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/releases/download/arc-2014.12/arc_gnu_2014.12_prebuilt_elf32_le_linux_install.tar.gz

the resultant executable includes a "norm" instruction which should not be used when the arcem is selected, at least according to:

  https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/wiki/compiler-options

Here is how to recreate:

echo '
# include <stdio.h>

int main() {
    printf("Hello, World!\n");
    return 0;
}
' > hello.c
arc-elf32-gcc -mcpu=arcem hello.c -o hello.elf -Wl,-Map=hello.map
arc-elf32-objdump -d hello.elf > hello.od

Examining hello.od shows a norm instruction used in the strlen function, and looking in hello.map indicates the strlen function comes from arc-elf32/lib/em/libc.a. Doing an objdump on libc.a shows several uses of the norm instruction.

I also notice there is an arc-elf32/lib/em/norm directory - which presumably is a version of the em target libraries built with the -mnorm switch, but both libraries are using the norm instruction.

Is it possible there is a bug allowing the toolchain to use norm instructions when -mcpu=arcem is selected?

Thanks

Jim Straus

**Comment by anthony-kolesov** [comment]
Hi Jim,

You are right. libc code for string and memory functions is hand-written on assembly and I see that in [strlen.S](https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/blob/arc-2.0-dev/newlib/libc/machine/arc/strlen.S) and [memcmp.S](https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/blob/arc-2.0-dev/newlib/libc/machine/arc/memcmp.S) `norm` instructions are used unconditionally, which causes an issue on default EM configuration. That, certainly, will be fixed in our next release, which however will be only in June. We also have plans for a patch release, but that will also happen only in a few weeks.

How much of a problem that poses for you? If this is a blocker, would be ok for you to rebuild toolchain from source or binary release is better?

Anton

**Comment by jstraus59** [comment]
Hi Anton,

Thanks for the quick response. It's not blocking me at the moment. I am building the toolchain myself and can apply a patch when available. Please keep me posted if a patch is made.

Thanks

Jim

**Comment by claziss** [comment]
Hi Jim. Please update your newlib folder with this commit: https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/commit/4393d2df011d57f3cbbd5e9742bc4a9d0e41a5f6. Please let us know how it is working.

**Comment by jstraus59** [comment]
That did the trick. Thanks.
