### ISSUE TITLE
Missing function definitions in newlib/libc/sys/arc/syscalls.c

### ISSUE THREAD

**Issue by jstraus59** [foss-for-synopsys-dwc-arc-processors/toolchain#49]
The stat_r and times_r function definitions are missing in newlib/libc/sys/arc/syscalls.c. The result is that an attempt to link an object file with a call to stat() or times() results in an "undefined reference" error.

Looking at newlib/libc/sys/arc/sys/syscalls.h it appears there is underlying support for these functions, so I am thinking this was just an oversight.

To recreate the problem using the prebuilt toolchain from https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/releases/download/arc-2014.12/arc_gnu_2014.12_prebuilt_elf32_le_linux_install.tar.gz do the following:

echo '
# include <sys/stat.h>
# include <sys/times.h>
# include <sys/types.h>
# include <unistd.h>

int main() {

```
struct stat statBuf;
stat("file", &statBuf);

struct tms tmsBuf;
times(&tmsBuf);
```

}
' > test.c
arc-elf32-gcc test.c 

which gives the following result:

/tmp/arc_gnu_2014.12_prebuilt_elf32_le_linux_install/bin/../lib/gcc/arc-elf32/4.8.3/../../../../arc-elf32/lib/libc.a(lib_a-sysstat.o): In function `stat':
/home/akolesov/ws/arc-2014.12/unisrc-4.8/newlib/libc/syscalls/sysstat.c:12: undefined reference to`_stat_r'
/tmp/arc_gnu_2014.12_prebuilt_elf32_le_linux_install/bin/../lib/gcc/arc-elf32/4.8.3/../../../../arc-elf32/lib/libc.a(lib_a-systimes.o): In function `times':
/home/akolesov/ws/arc-2014.12/unisrc-4.8/newlib/libc/syscalls/systimes.c:10: undefined reference to`_times_r'
collect2: error: ld returned 1 exit status

Thanks,

Jim Straus

**Comment by anthony-kolesov** [comment]
Hi Jim,

I believe those functions are absent because they are system-specific and cannot be implemented in a way generic for ARC. `stat` system call is for file system interaction, and in our baremetal newlib there is no file system implementation at all. The same holds true for `times` since this is a "current process time" and there is no notion of "current process" in our baremetal application based on newlib without OS. That means that to use those functions you should provide your own implementations of those functions that are opropriate to your SoC, board and maybe RTOS.

Though the same is true for many other system calls, but there instead we have a stub implementation where calling for example `puts` will cause a software interrupt, which is just not implemented and should be provided by board support package. I've sent a question to our newlib maintainer on whether `stat` and `times` should be the same, or there is a reason for them to be special.

**Comment by jstraus59** [comment]
Hi Anton,

Thanks again for the quick response. 

Note that the similar functions fstat and gettimeofday both link without an error and are implemented in newlib/libc/sys/arc/syscalls.c with a syscall to be handled by a BSP, debugger or simulation semihost.  It seems these should be implemented similarly. stat is very similar to fstat, and even if process specific values cannot be provided for times it should not cause a linker error. This is why I suspect that these two missing functions are simply an oversight.

Thanks for passing this along to the newlib maintainers. I will be interested to hear their response.

Jim

**Comment by anthony-kolesov** [comment]
Should be fixed by https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/commit/68d07f46af7d2236a92bd15af7b4520d750593db.
