### ISSUE TITLE
IDE for Windows from 2022.09 RC1 does not work

### ISSUE THREAD

**Issue by kolerov** [foss-for-synopsys-dwc-arc-processors/toolchain#495]
When I try to build a simple "Hello, World!" project for any target nothing happens and I see this error:

```
make all 
'Building file: ../src/hello_hs38_linux.c'
'Invoking: ARC GNU C Compiler'
C:\arc_gnu\bin\arc-elf32-gcc.exe -mcpu=hs -O0 -g3 -Wall -c -fmessage-length=0 -gdwarf-2 -MMD -MP -MF"src/hello_hs38_linux.d" -MT"src/hello_hs38_linux.o" -o "src/hello_hs38_linux.o" "../src/hello_hs38_linux.c"
make: *** [src/subdir.mk:20: src/hello_hs38_linux.o] Error -1073741515
"make all" terminated with exit code 2. Build might be incomplete.
```

When I try to do the same step in command line an error occurs:

![tempsnip](https://user-images.githubusercontent.com/516974/206150582-75bb3dc6-6d14-425a-aa04-5f141e914910.png)

The problem is that `arc-elf32-gcc` (and `arc-elf32-g++`) depends on `libwinpthread-1.dll` and this dependency is missing:

![Capture](https://user-images.githubusercontent.com/516974/206150832-f708217f-f486-4cb1-8646-ee53dee6e765.PNG)

Thus there are 2 ways to fix it:

1. Link a toolchain for Windows statically.
2. Copy missing dll to bin directory.

**Comment by abrodkin** [comment]
So that happens because MinGW used for canadian cross build was configured with Pthreads (`CT_THREADS_POSIX=y`), basically vanilla config of CT-NG: https://github.com/crosstool-ng/crosstool-ng/blob/master/samples/x86_64-w64-mingw32/crosstool.config.

If default threads implementation is used, that problem don't exist.
As a matter of fact, for `arc-20221.09` we used https://github.com/crosstool-ng/crosstool-ng/blob/master/samples/i686-w64-mingw32/crosstool.config before https://github.com/crosstool-ng/crosstool-ng/commit/a8d2c2e1fac2106da65dbaf768d32857428fe621 so Pthreads were not used.

We'll used older MinGW build for `arc-2022.09` as well and later will re-build new MinGW with native Windows threads.
