### ISSUE TITLE
A lost commit in arc-2022.09

### ISSUE THREAD

**Issue by kolerov** [foss-for-synopsys-dwc-arc-processors/toolchain#502]
There is at least one lost commit in arc-2022.09 branch: https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/commit/fc50a17ddc79e048f9047cac0713cb8ab9b817be. It leads to a regression: https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/issues/259. Seems like it's necessary to check whether other commits may be lost.

**Comment by abrodkin** [comment]
@shahab-vahedi could you please cherry-pick at least mentioned https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/commit/fc50a17ddc79e048f9047cac0713cb8ab9b817be in https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/tree/arc-2022.09 so that we may create RC2 soonish.

**Comment by shahab-vahedi** [comment]
It is cherry-picked both in [2022.09](https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/commit/3600e6b8816d9819692f3e3fe24e8d38e2bbc293) and [arc64](https://github.com/foss-for-synopsys-dwc-arc-processors/newlib/commit/713d19837e52335043b799d82bf36d815d08b85e) branches. However, I couldn't test it due to #507.

**Comment by abrodkin** [comment]
Is a part of `arc-2022.09-rc2` available here https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/releases/tag/arc-2022.09-rc2
