### ISSUE TITLE
Source Files Missing in Recent Releases

### ISSUE THREAD

**Issue by robfallone** [foss-for-synopsys-dwc-arc-processors/toolchain#525]
It seems like the source files package is missing from the recent releases (i.e https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/releases/tag/arc-2022.09-release).

Good example:
The [2021.03](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/releases/tag/arc-2021.03-release) has a [arc_gnu_2021.03_sources.tar.gz](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/releases/download/arc-2021.03-release/arc_gnu_2021.03_sources.tar.gz) file which is needed to rebuild the tools manually.

Can we get these packages added to the releases OR provide steps to get the sources myself?

**Comment by yaroslavsadin** [comment]
Hi @robfallone ,

This is to let you know that we did include the sources in the latest [2023.03 release](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/releases/tag/arc-2023.03-release), please check and let us know if you have any further issues. Otherwise, can we close this one?

Best regards,
Yaroslav
