### ISSUE TITLE
gdbserver: bad r13 register state during asm instructions single step debugging

### ISSUE THREAD

**Issue by shahab-vahedi** [foss-for-synopsys-dwc-arc-processors/toolchain#545]
It looks like on every single step by debug command, linux kernel provides previously saved value for r13, even if instruction changes the r13 register value it will have no effect and previously saved value will be returned. This issue occurs on ARCv3 (arc32 and arc64) Linux.

![ss-r13-issue](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/assets/16524902/d6f156f7-0ee0-44b7-97cb-adc2ace4e90b)

sample: [gdb-hs5-r13-lnx.tgz](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/files/11551438/gdb-hs5-r13-lnx.tgz)

**Comment by luismgsilva** [comment]
The problem stems from an incorrect implementation of the ptrace in the Linux kernel for ARC. 

The issue arises from a flawed utilization of the "&" operator. 

```
$ cat linux/arch/arc/kernel/ptrace.c
..
72	membuf_store(&to, &ptregs->r13);
..
```

In this scenario, it is intended to obtain the value stored in the r13 register. However, due to a misplaced "&" operator, it inadvertently retrieves the memory address associated with the r13 register.

A patch has been made available to address this issue.
https://github.com/foss-for-synopsys-dwc-arc-processors/linux/pull/152
