### ISSUE TITLE
Python3 crashing when built for snps_arc32_defconfig

### ISSUE THREAD

**Issue by jzbydniewski** [foss-for-synopsys-dwc-arc-processors/toolchain#596]
I'm using branch arc-2023.09, config snps_arc32_defconfig
I added python3 in menuconfig.

After running the vmlinux in nSIM, I can see the following crash when trying to run python3

```
# python3
potentially unexpected fatal signal 11.
Path: /usr/bin/python3.11
CPU: 0 PID: 129 Comm: python3 Not tainted 5.16.0 foss-for-synopsys-dwc-arc-processors/buildroot#2
Invalid Read @ 0x00000054 by insn @ 0x2011dab2
  @off 0x114ab2 in [/usr/lib/libpython3.11.so.1.0]  VMA: 0x20009000 to 0x20251000
ECR: 0x00050100 EFA: 0x00000054 ERET: 0x2011dab2
STAT: 0x80080a82 [IE U     ]   BTA: 0x2011da98
 SP: 0x5ff0c5e4  FP: 0x00000033 BLK: 0x20167366
r00: 0x5ff0c618 r01: 0x00000000 r02: 0x202774d4
r03: 0x00000001 r04: 0x00000001 r05: 0x00000018
r06: 0xe34a2302 r07: 0x203f11b8 r08: 0x000000d6
r09: 0x00040003 r10: 0x00040003 r11: 0x00000006
r12: 0x2008e018 r13: 0x40014000 r14: 0x20315e7a
r15: 0x5ff0c618 r16: 0x00000001 r17: 0x00000001
r18: 0x400b126c r19: 0x2031d998 r20: 0x2031d998
r21: 0xffffffff r22: 0x2031d784 r23: 0x20407718
r24: 0x20407610 r25: 0x203e3320
Segmentation fault
```

**Comment by jzbydniewski** [comment]
From what I see it doesn't matter whether I choose glibc or uClibc in toolchain setting.

**Comment by jzbydniewski** [comment]
With older branch 2022.09 I don't see this issue, with both uClibc and glibc. Hower, I can see it is using also older version of the python3 package.

**Comment by xxkent** [comment]
Hi @jzbydniewski
I did a quick trace analysis near the place where python 3 crashes and it looks like this problem is the same as this one:
https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/issues/594

The result of the 'mac' instruction was never saved/used until the crash.

```
mac            0,r0,0x1c : r58 <= 0x00006280 : r59 <= 0xa4191878 *
add_s          r0,r0,r1 : (w0) r0 <= 0x2033deea *
ld_s           r1,[r0] : lw [0x2033deea] => 0x00000000 : (w1) r1 <= 0x00000000 *
add            r1,r1,0x1 : (w0) r1 <= 0x00000001 *
...
st_s           r1,[r0] : sw [0x2033deea] <= 0x00000001 *
...
ld_s           r14,[r0] : lw [0x5fe5f51c] => 0x2033deea : (w1) r14 <= 0x2033deea *
...
ld_s           r0,[r14,0x4] : lw [0x2033deee] => 0x00000000 : (w1) r0 <= 0x00000000 *
ld_s	       r0,[r0,0x54] <---   Crash is here
```

**Comment by kolerov** [comment]
@gmazurkiewicz @jzbydniewski Please, check it again. It must be already fixed by https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/pull/119. Also, the same PR fixes these Issues too:

1. https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/issues/597
2. https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/issues/594

It will be necessary to completely rebuild Buildroot images.

**Comment by kolerov** [comment]
@claziss @abrodkin Seems like it's also necessary to update GCC tag in Buildroot. E.g., add `arc-2023.09.1-release` tag and add a new hash to Buildroot or update `arc-2023.09-release` tag and update hash in `package/gcc/gcc.hash`. The fix is pushed in `arc-2023.09` but Buildroot fetches `arc-2023.09-release` tag.

**Comment by jzbydniewski** [comment]
Thanks, I can confirm that fix in toolchain resolved the issue.

**Comment by abrodkin** [comment]
Fixed with https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/aaef101542da6023edc3e35938e1f3144ee55c85
