### ISSUE TITLE
How to debug archs36 dual core simultaneously

### ISSUE THREAD

**Issue by 111yyyu** [foss-for-synopsys-dwc-arc-processors/toolchain#601]
How to dual-core debug ARCHS36 in ARC GNU IDE 2023.03 Eclipse environment. In other words, how to specify a core for debugging? Currently, it is found that after selecting the Development system: Custom configuration file in the IDE, the Target Core cannot be selected. How can I solve this problem？
![debug_cfg_custom](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/assets/166588502/8ea70844-4b29-4702-94c9-7b157003174a)

**Comment by abrodkin** [comment]
@kolerov could you please take a look at this one once you're back next week?

**Comment by abrodkin** [comment]
@111yyyu what you're asking is adding support for simultaneous debugging of the multicore system, right? In that case adding any kind of script won't help. That's because interactive debugging of the multicore systems requires special handling of multiple instances of all views/menus at the same time. Think of 2 separate "registers" or "instruction trace" views, ability to set break-pont specifically for a certain core of the cluster etc. That functionality is not currently supported by ARC GNU IDE and we have no plans for adding that.
But since plugin which is used for creation of ARC GNU IDE from Eclise CDT is available in sources (https://github.com/foss-for-synopsys-dwc-arc-processors/arc_gnu_eclipse), you're free to add required functionality yourself.

**Comment by 111yyyu** [comment]
@abrodkin Thanks for reply！
