### ISSUE TITLE
-mshift-assist no longer supported in 2015.06

### ISSUE THREAD

**Issue by jstraus59** [foss-for-synopsys-dwc-arc-processors/toolchain#64]
The prebuilt [2015.06](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/releases/download/arc-2015.06/arc_gnu_2015.06_prebuilt_elf32_le_linux_install.tar.gz) toolchain no longer supports the gcc _-mshift-assist_ option that was supported in the prebuilt [2014.12](https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/releases/download/arc-2014.12/arc_gnu_2014.12_prebuilt_elf32_le_linux_install.tar.gz) release:

2015.06:

```
$ arc_gnu_2015.06_prebuilt_elf32_le_linux_install/bin/arc-elf32-gcc --target-help | grep shift
  -mbarrel-shifter            Generate instructions supported by barrel shifter
```

2014.12:

```
$ arc_gnu_2014.12_prebuilt_elf32_le_linux_install/bin/arc-elf32-gcc --target-help | grep shift
  -mbarrel-shifter            Generate instructions supported by barrel shifter
  -mshift-assist              Enable shift assist instructions for ARCv2
```

I could not find any references to this in the notes. Is this intentional?

Thanks

Jim Straus

**Comment by anthony-kolesov** [comment]
Hi Jim,

-mshift-assist has been removed, because even when this option was enabled, GCC still wasn't generating any of respective instructions, so to avoid confusion option has been removed.

As of the assembler, in cause you intend to write shift-assist instruction manually, then assembler always accepts all valid ARC mnemonics - that is, when assembler sees one of "shift-assist" instructions it just encodes it, it doesn't try to check if this extension is enabled or not.

**Comment by jstraus59** [comment]
Thanks for the explanation.
