### ISSUE TITLE
Differences between mainline GCC and Synopsys GCC

### ISSUE THREAD

**Issue by jurobystricky** [foss-for-synopsys-dwc-arc-processors/toolchain#83]
I am curious what is the principal difference between the GCC  maintained by Synopsys and the upstreamed version. The Synopsys version seems to  be still at GCC 4.8.5, but there is already GCC 6.2.x with ARC support.

**Comment by vineetgarc** [comment]
AFAIK (@claziss is the best person to answer this BTW), upstream 6.2 still lacks some of the patches needed for ARCv2 ISA support (these were stuck in pipe due to review delays with upstream maintainers). Also note that there's a gcc ABI change between 4.8.x and upstream (in terms of 64-bit alignment in reg pairs)

**Comment by claziss** [comment]
The upstream version of ARC gcc is not complete, and also has a number of bugs which are handled in our repository. A number of patches are submitted to fix this difference, but they are painfully slow reviewed.

**Comment by fbedard** [comment]
Follow GCC mailing list for further updates.  We are working with FSF to get patches reviewed and accepted ASAP.
