### ISSUE TITLE
Useless routines used instead of optimized instructions

### ISSUE THREAD

**Issue by calandoa** [foss-for-synopsys-dwc-arc-processors/toolchain#97]
Hello,

When compiling, gcc is not using expected ARC instructions despites the options I provide.

All the options I am using are:
```
arc-elf32-gcc
-fcommon
-mav2em
-mlong-calls
-mno-sdata
-mcpu=arcem
-mdiv-rem
-mbarrel-shifter
-mspfp
-mdpfp
-mdiv-rem
-mnorm
-mswap
-mcode-density
-mmpy-option=wlh2
```

During linking process (with my own script and libraries), the first problem I have is that I get many messages (for nearly each function) like:
```
undefined reference to `__st_r13_to_r15'
undefined reference to `__ld_r13_to_r15'
undefined reference to `__ld_r13_to_r15_ret'
```

It seems that instead of using ENTER_S and LEAVE_S instructions to save/restore multiple regsiters on the stack, gcc is using librayr routines. Because I am using `-mcode-density`, I would expect gcc to use the appropriate instructions. Note also that this problem disappear  if I use `-mno-millicode`, but the code generated is not optimized at all.

The second problem I also have is:
```
undefined reference to `_mpymu'
undefined reference to `_mpyu'
```
Again, because I am using `-mmpy-option=wlh2`, I would expect gcc not to use separate multiply routines.

**Comment by claziss** [comment]
Hi,
For the enter/leave issue, GCC doesn't use leave_s and enter_s due to how those instructions are saving/restoring the registers as compared to the way how ABI describe the saving of the registers, though we consider to add this latter on only for bare metal apps.

For the linking issue, u miss linking with libgcc which has the implementation of the missing symbols.

For use of mpy, I would expect the same thing. Please come with more info on this subject (i.e., preprocess files + compiler options) to be able to debug your issue.

To get the code optimized, you need to pass an optimization option to the compiler such as -O2 or -O3.

**Comment by calandoa** [comment]
Thanks for your swift answer!

Ok, so for ENTER/LEAVE this is something not yet implemented.

For MPY, I am not sure to understand your answer. The HW I am using provides this instruction, and I am asking gcc to use it with `-mmpy-option=wlh2` as stated by the doc. There should be no separate library called to do this.

The linker errors I get are not really the problem, they are only showing that there was a problem during compilation, and I guess MPY instruction should be use whatever -O optimization is used or not.

Should I understand that MPY is also not implemented as a CPU instruction yet? I was more hoping something like conflicting gcc options I am giving.

Note also that I tried with arc-releases and arc-staging versions of gcc.

**Comment by claziss** [comment]
Hi,

In order to debug your issue, I need more info like an example that shows your issue. For example, I will make a small test in the following lines to show how mpy is generated:

My setup:

arc-elf32-gcc --version
arc-elf32-gcc (ARCompact/ARCv2 ISA elf32 toolchain arc-2016.09-rc1-2-gb04a7b5) 6.2.1 20160824
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

and I use this code:

``` c
int foo (int a, int b)
{
  return a*b;
}
```

To compile, I use the following command:

arc-elf32-gcc -fcommon  -mlong-calls -mno-sdata -mcpu=arcem -mdiv-rem -mbarrel-shifter -mspfp -mdpfp -mdiv-rem -mnorm -mswap -mcode-density -mmpy-option=wlh2 t01.c -S -O2

Please note -mav2em is deprecated option!

I obtain this:

``` asm
        .file   "t01.c"
        .cpu EM
        .section        .text
        .align 4
        .global foo
        .type   foo, @function
foo:
        j_s.d [blink]
        mpy_s r0,r0,r1
        .size   foo, .-foo
        .ident  "GCC: (ARCompact/ARCv2 ISA elf32 toolchain arc-2016.09-rc1-2-gb04a7b5) 6.2.1 20160824"
```

As you can see, I am getting the mpy instruction generated.

Thanks

**Comment by calandoa** [comment]
I have been investigating more in details the functions that were causing the errors... and this is my mistake! These functions are actually using in plain text the calls `_mpymu(...)` in the C file... (I am importing a project I did not wrote myself) I was actually assuming the same kind of behavior than for ENTER/LEAVE and did not dig enough before requesting your help, sorry for that. 

Multumesc Claudiu !

**Comment by claziss** [comment]
Cu placere.

P.S. If you build the toolchain by yourself please use the latest sources. They are located in the default branch of each repo.
